import type { Metadata } from 'next';
import { LegalPage } from '@/components/legal-page';

export const metadata: Metadata = {
  title: 'Datenschutz',
  description: 'Datenschutzerklärung für die PipeBot-Website von Pipeline AI Solutions.',
  alternates: { canonical: '/datenschutz/' },
};

export default function DatenschutzPage() {
  return (
    <LegalPage eyebrow="Rechtliches" title="Datenschutzerklärung" intro="Informationen zur Verarbeitung personenbezogener Daten auf pipebot.at. Stand: 21. September 2026.">
      <section><h2>1. Verantwortlicher.</h2><p><strong>Pipeline AI Solutions</strong><br />Paul Hölzl<br />Edholz 10, 4115 Kleinzell im Mühlkreis, Österreich<br />E-Mail: <a href="mailto:office@pipeline-solutions.at">office@pipeline-solutions.at</a><br />Telefon: <a href="tel:+4368120764203">+43 681 207 64 203</a></p></section>
      <section><h2>2. Allgemeines.</h2><p>Wir verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung dieser Website, zur Bearbeitung von Anfragen oder zur Erfüllung vertraglicher und gesetzlicher Pflichten erforderlich ist. Maßgeblich sind insbesondere die Datenschutz-Grundverordnung (DSGVO) und die anwendbaren österreichischen Datenschutzbestimmungen.</p></section>
      <section><h2>3. Hosting und technische Zugriffsdaten.</h2><p>Diese Website wird über Railway bereitgestellt. Beim Aufruf können technisch erforderliche Daten verarbeitet werden, insbesondere IP-Adresse, Datum und Uhrzeit, aufgerufene Seite, Browser- und Geräteinformationen sowie Fehler- und Sicherheitsprotokolle.</p><p>Die Verarbeitung erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse liegt in der sicheren und zuverlässigen Bereitstellung der Website. Railway kann Daten in den USA und weiteren Ländern verarbeiten. Für Übermittlungen in Drittländer nennt Railway insbesondere das EU-US Data Privacy Framework und Standardvertragsklauseln als Schutzmechanismen. Weitere Informationen finden Sie in der <a href="https://railway.com/legal/privacy" target="_blank" rel="noreferrer">Datenschutzerklärung von Railway</a>.</p></section>
      <section><h2>4. Kontaktaufnahme.</h2><p>Wenn Sie uns per E-Mail oder Telefon kontaktieren, verarbeiten wir die von Ihnen übermittelten Angaben zur Bearbeitung Ihrer Anfrage und für mögliche Anschlussfragen. Rechtsgrundlage ist je nach Inhalt der Anfrage Art. 6 Abs. 1 lit. b oder lit. f DSGVO.</p><p>Wir speichern Anfragen nur so lange, wie dies für die Bearbeitung und mögliche Folgekommunikation erforderlich ist; gesetzliche Aufbewahrungspflichten bleiben unberührt.</p></section>
      <section><h2>5. PipeBot-Chat, kostenloser Website-Test und KI-Verarbeitung.</h2><p>PipeBot ist ein KI-Assistent. Wenn Sie den Chat verwenden, werden Ihre eingegebenen Nachrichten und bis zu zwölf Nachrichten des aktuellen Gesprächs über unsere eigene Schnittstelle an Neokens übermittelt. Neokens leitet die für die Antwort erforderlichen Inhalte an den für das gewählte Modell eingesetzten KI-Anbieter weiter.</p><p>Beim kostenlosen Website-Test verarbeiten wir zusätzlich die von Ihnen eingegebene URL sowie öffentlich abrufbare Inhalte der betreffenden Startseite und bis zu drei Stylesheets derselben Domain. Daraus werden eine temporäre Wissensbasis, Farbauswahl, Begrüßung und Beispielfragen erstellt. Verwenden Sie den Test nur für öffentlich erreichbare Websites, die Sie zu diesem Zweck analysieren dürfen.</p><p>Die Testkonfiguration wird nicht in einer Datenbank gespeichert. Sie liegt höchstens 30 Minuten im Arbeitsspeicher des Servers und umfasst maximal acht Testfragen. Zur Missbrauchsbegrenzung wird die anfragende IP-Adresse ausschließlich als nicht rückrechenbarer Hash in einem kurzlebigen Zähler verarbeitet; technische Hosting-Protokolle bleiben davon unberührt.</p><p>Die Verarbeitung erfolgt zur Beantwortung Ihrer freiwilligen Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, wenn Ihre Anfrage auf einen Vertrag oder vorvertragliche Maßnahmen gerichtet ist, andernfalls Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse liegt in einer schnellen, verständlichen Produktdemonstration und dem Schutz des Dienstes vor Missbrauch. Die Daten werden nicht für Werbeprofile verwendet.</p><p>Wir führen für diese Website keine eigene Chat-Datenbank und speichern den Gesprächsinhalt nicht dauerhaft. Der im Browser sichtbare Verlauf besteht nur für die geöffnete Seite. Neokens gibt an, Prompt- und Antwortinhalte nur vorübergehend für die Weiterleitung zu verarbeiten; API-Metadaten wie Zeitpunkt, Modell, Tokenzahl und Status werden laut Neokens bis zu zwölf Monate gespeichert.</p><p>Neokens und nachgelagerte Anbieter können Daten in den USA oder anderen Drittländern verarbeiten. Neokens nennt Standardvertragsklauseln und weitere geeignete Garantien als Schutzmechanismen. Weitere Informationen finden Sie in der <a href="https://v2.neokens.com/legal/privacy" target="_blank" rel="noreferrer">Datenschutzerklärung von Neokens</a> und im dort verlinkten Data Processing Addendum.</p><p>Geben Sie im Chat keine besonderen Kategorien personenbezogener Daten, Zugangsdaten oder vertraulichen Geschäftsgeheimnisse ein.</p></section>
      <section><h2>6. Cookies, lokale Speicherung und Analyse.</h2><p>Diese Version der Website setzt keine eigenen Analyse-, Marketing- oder Trackingdienste ein. Die Auswahl des hellen oder dunklen Farbschemas wird ausschließlich lokal in Ihrem Browser gespeichert. Es werden keine externen Schriftarten oder Social-Media-Inhalte eingebettet.</p></section>
      <section><h2>7. Empfänger und Auftragsverarbeitung.</h2><p>Innerhalb unseres Teams erhalten nur jene Personen Zugriff auf personenbezogene Daten, die diese zur Bearbeitung benötigen. Externe Dienstleister setzen wir nur ein, soweit dies für Hosting, Kommunikation, KI-Verarbeitung oder Projektabwicklung erforderlich ist und eine datenschutzrechtliche Grundlage besteht.</p></section>
      <section><h2>8. Ihre Rechte.</h2><p>Sie haben – soweit die gesetzlichen Voraussetzungen vorliegen – das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Zur Ausübung Ihrer Rechte schreiben Sie an <a href="mailto:office@pipeline-solutions.at">office@pipeline-solutions.at</a>.</p><p>Außerdem haben Sie das Recht, Beschwerde bei einer Datenschutzaufsichtsbehörde einzulegen. In Österreich ist dies die Österreichische Datenschutzbehörde.</p></section>
      <section><h2>9. Datensicherheit und Aktualisierung.</h2><p>Wir setzen angemessene technische und organisatorische Maßnahmen ein, um Daten gegen Verlust, Missbrauch und unbefugten Zugriff zu schützen. Wir passen diese Datenschutzerklärung an, wenn sich die Website, eingesetzte Dienste oder rechtliche Anforderungen ändern.</p></section>
    </LegalPage>
  );
}
